server:
  port: 18088
spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://192.168.43.33:3306/shop_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true

#启用feign服务熔断
feign:
  hystrix:
    enabled: true

mybatis:
  type-aliases-package: cn.lx.shop.user.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰
    map-underscore-to-camel-case: true
