server:
  port: 18089
spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://192.168.43.33:3306/shop_order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
  rabbitmq:
    port: 5672
    username: admin
    password: admin
    host: 192.168.43.33


  redis:
    database: 3
    host: 192.168.43.33
    port: 6379


  main:
    allow-bean-definition-overriding: true


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true

#启用feign服务熔断
feign:
  hystrix:
    enabled: true

mybatis:
  type-aliases-package: cn.lx.shop.order.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰
    map-underscore-to-camel-case: true


#hystrix 配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
          #修改hystrix的隔离策略
          strategy: SEMAPHORE

#订单超时交换机和队列
mq:
  order:
    directExchange: exchange.order
    deadLetterQueue: queue.dead.order
    queue: queue.order
  pay:
    queue: queue.pay
