server:
  port: 18090
spring:
  application:
    name: pay

  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    port: 5672
    username: admin
    password: admin
    host: 192.168.43.33


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true

#启用feign服务熔断
feign:
  hystrix:
    enabled: true


#hystrix 配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
          #修改hystrix的隔离策略
          strategy: SEMAPHORE



#微信支付信息配置
weixin:
  appid: wx8397f8696b538317
  mch_id: 1473426802
  signKey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
  notify_url: http://192.168.43.210:18090/weixin/pay/notify/url


#位置支付交换机和队列
mq:
  pay:
    directExchange: exchange.pay
    queue: queue.pay
    routingKey: queue.pay
